### ISSUE TITLE
Restrict Metrics Configuration by Default

### ISSUE THREAD

**Issue by Merenon** [putsi/privatecollaborator#7]
I'm a fan of "security by default" and would restrict the metrics section within the default collaborator.config to prevent undesired exposure (although not really sensitive): 
https://github.com/putsi/privatecollaborator/blob/769b478f4bffa7b41a6114b332f8d201be8a991a/collaborator.config#L42-L44

```
"metrics": {  
   "path" : "burp-metrics-path", 
   "addressWhitelist" : ["127.0.0.1/32"]
 }
```

**Comment by putsi** [comment]
Fixed in f1532013a2703bce1c964601a4e76a1d27109e63, thanks!
