### ISSUE TITLE
Incoming SMTP not allowed in Amazon AWS by default

### ISSUE THREAD

**Issue by incogbyte** [putsi/privatecollaborator#8]
i deploy on amazon i got this bug :/ i follow the tutorial.. i setup godaddy..

![bug_01](https://user-images.githubusercontent.com/53656948/64667680-fbd3ef00-d430-11e9-9511-e7d966972899.png)

**Comment by putsi** [comment]
Hi,

Amazon doesn't like incoming SMTP connections by default and requires you to fill some forms:
https://forums.aws.amazon.com/thread.jspa?threadID=152702

I'll update information about that in the related blog post ASAP.

**Comment by putsi** [comment]
About the error in `Polling server connection`, are you able to access the polling ports directly with e.g. web browser?
