### ISSUE TITLE
Renew Certificates Script is Missing Copy

### ISSUE THREAD

**Issue by Merenon** [putsi/privatecollaborator#9]
Based on the `install.sh` script, the Let's Encrypt certificates need to be copied to the desired collaborator directory. This is missing within the `renewcert.sh` script:

```
CERT_PATH=/etc/letsencrypt/live/$DOMAIN
mkdir -p /usr/local/collaborator/keys/
cp $CERT_PATH/privkey.pem /usr/local/collaborator/keys/
cp $CERT_PATH/fullchain.pem /usr/local/collaborator/keys/
cp $CERT_PATH/cert.pem /usr/local/collaborator/keys/
```

**Comment by putsi** [comment]
The certs are now symlinked and not copied which should fix this issue. 
Thank you for your issue report.
